### ISSUE TITLE
Add command to list pull requests

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/github-api-cli#1]
This command should fetch all public PR from the user.

Suggested command:

```
gac list pr <username>
```

Output: Could be a list or table of content.

Reference:

[API for fetching all PR](https://api.github.com/search/issues?q=type:pr+author:"<USERNAME>"&sort=created&order=desc)

**Comment by prithvijit-dasgupta** [comment]
Hey @thamaraiselvam I would like to work on this.

**Comment by thamaraiselvam** [comment]
You are on it. Assigned you. Don't forget to write unit tests 😉

**Comment by prithvijit-dasgupta** [comment]
![image](https://user-images.githubusercontent.com/55779009/67230987-0932bf00-f45c-11e9-9fa2-94ddf6773ed9.png)

Currently getting something like this^? Should I proceed with this table format?

**Comment by thamaraiselvam** [comment]
That's really cool. Let's go with your formatting.

And command lets have like this?

```
list pr <username>
```

There are lots of commands under list, So they will become sub commands of it.

**Comment by prithvijit-dasgupta** [comment]
Ok making a commit with the initial changes...Need to look at cobra to get this functionality

**Comment by thamaraiselvam** [comment]
@prithvijit-dasgupta  I have added list command, Add PR command under that. check followers command for reference

**Comment by thamaraiselvam** [comment]
@prithvijit-dasgupta can you please fix merge conflicts and move command into the list command?

**Comment by prithvijit-dasgupta** [comment]
@thamaraiselvam yeah i will do it by tomorrow night

**Comment by prithvijit-dasgupta** [comment]
@thamaraiselvam hey can you review it? I am sorry for such a huge delay...just got too busy
