### ISSUE TITLE
Update Go Report Card badge on Readme

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/github-api-cli#17]
Update [Go Report Card ](https://goreportcard.com/report/github.com/thamaraiselvam/github-api-cli) badge  on Readme file

Reference:
https://goreportcard.com/badge/github.com/thamaraiselvam/github-api-cli?style=flat-square

Currently, Other batches are using `style=for-the-badge` but goreportcard does not support that style. 
but `style=flat-square` looks very similar, maybe adding width and height on the image, can make it look alike other batches.
PR From **FIRST TIME CONTRIBUTORS** Welcome.

**Comment by andrewgcodes** [comment]
Claimed

**Comment by ghost** [comment]
Gave both badges a static height and width similar to other badges. Does this look good to you? 
 
![image](https://user-images.githubusercontent.com/21277645/68068933-039e7880-fd7c-11e9-9d7a-f535267500ef.png)


P.S. I'm a newbie contributor.

**Comment by thamaraiselvam** [comment]
@hasanadeem  I appreciate your contribution.

Already there is a PR raised https://github.com/thamaraiselvam/github-api-cli/pull/19  he has changed all existing badge size to `style=flat-square`. but he did not add a go report card yet.

can you raise a pull request by adding it?

**Comment by thamaraiselvam** [comment]
@hasanadeem Are you working on it?

**Comment by thamaraiselvam** [comment]
resolved
