### ISSUE TITLE
Update godoc reference badge on Readme

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/github-api-cli#21]
Update [go doc](https://godoc.org/github.com/thamaraiselvam/github-api-cli) for this cli application.

Add this new badge after coverage tag

badge link:

https://godoc.org/github.com/thamaraiselvam/github-api-cli?status.svg

**Comment by gonzalezlrjesus** [comment]
Hi, I could try to add the badge.is it yet allowed?

**Comment by thamaraiselvam** [comment]
@gonzalezlrjesus thank you for showing your interest but i am looking for first time contributor to oss. lets wait for couple of days if no one picking up. you can do it.

Sorry for the denial but I want to on board a fresh contributor.

**Comment by gonzalezlrjesus** [comment]
Ok, no problem, I will be pending.

**Comment by thamaraiselvam** [comment]
@gonzalezlrjesus  seems like no is picking up. can you do it?

**Comment by gonzalezlrjesus** [comment]
Done.

**Comment by thamaraiselvam** [comment]
Thanks, @gonzalezlrjesus  for the PR. I merged it. 

can you do this as well? https://github.com/thamaraiselvam/github-api-cli/issues/17

**Comment by gonzalezlrjesus** [comment]
Ok, i just did it.

**Comment by thamaraiselvam** [comment]
Thanks @gonzalezlrjesus  pr merged, Happy hacking.
