### ISSUE TITLE
Add command to list all following 

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/github-api-cli#4]
This command should fetch all the following users of a user.

Suggested command:

gac list following <username>

Output: Could be a list or table of content.

Reference:

[API for the fetching following](https://api.github.com/users/thamaraiselvam/following)

**Comment by raf924** [comment]
Hey is there any specific information you would like displayed for the following users?

**Comment by thamaraiselvam** [comment]
Just `login` and `html_url` is enough
