### ISSUE TITLE
Add brew installer

### ISSUE THREAD

**Issue by thamaraiselvam** [thamaraiselvam/github-api-cli#6]
People are able to install this cli application via brew command.
Also, Readme should be updated.

**Comment by r-i-c-h** [comment]
When you say "*Also*, Readme should be updated" - What is the first part of the request?

**Comment by thamaraiselvam** [comment]
How to Tap and Brew install commands should be updated in Readme file

**Comment by thamaraiselvam** [comment]
@r-i-c-h  Do you want to take it? If not I will work on it

**Comment by r-i-c-h** [comment]
@thamaraiselvam all you buddy!
